CREATE TABLE IF NOT EXISTS SystemInfo (
	version VARCHAR(20) NOT NULL,
    migration INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Accounts (
	id VARCHAR(36) PRIMARY KEY,
    type SET('free', 'premium') DEFAULT 'free'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Users (
    id VARCHAR(36) PRIMARY KEY,
	accountId VARCHAR(36) NOT NULL,
    firstName VARCHAR(200) NOT NULL,
    lastName VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    beltColor VARCHAR(200) NOT NULL,
    stripeCount INT DEFAULT 0,
    canRankUp BOOLEAN DEFAULT FALSE,
    hashedPassword VARCHAR(60),
	salt VARCHAR(36) UNIQUE,
    deletedAt TIMESTAMP NULL,
	FOREIGN KEY (accountId)
		REFERENCES Accounts (id)
		ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Programs (
	id VARCHAR(36) PRIMARY KEY,
	accountId VARCHAR(36) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    cycleCount INT DEFAULT 1,
    cycleType SET('years', 'months', 'weeks', 'days') DEFAULT 'years',
    attendancePerCycle INT DEFAULT 1,
    deletedAt TIMESTAMP NULL,
	FOREIGN KEY (accountId)
		REFERENCES Accounts (id)
		ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Roles (
	id VARCHAR(36) PRIMARY KEY,
	accountId VARCHAR(36) NOT NULL,
    programId VARCHAR(36) NOT NULL,
    userId VARCHAR(36) NOT NULL,
    role SET('admin', 'owner', 'instructor', 'student') DEFAULT 'student',
	FOREIGN KEY (accountId)
		REFERENCES Accounts (id)
		ON DELETE CASCADE,
	FOREIGN KEY (programId)
		REFERENCES Programs (id)
		ON DELETE CASCADE,
	FOREIGN KEY (userId)
		REFERENCES Users (id)
		ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Attendance (
	id VARCHAR(36) PRIMARY KEY,
    programId VARCHAR(36) NOT NULL,
    userId VARCHAR(36) NOT NULL,
    beltColor VARCHAR(200) NOT NULL,
    stripeCount INT NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (programId)
		REFERENCES Programs (id)
		ON DELETE CASCADE,
	FOREIGN KEY (userId)
		REFERENCES Users (id)
		ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS News (
	id VARCHAR(36) PRIMARY KEY,
	programId VARCHAR(36) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message text NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	createdBy VARCHAR(36),
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	updatedBy VARCHAR(36),
	FOREIGN KEY (programId)
		REFERENCES Programs (id)
		ON DELETE CASCADE,
	FOREIGN KEY (createdBy)
		REFERENCES Users (id),
	FOREIGN KEY (updatedBy)
		REFERENCES Users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Schedules (
	id VARCHAR(36) PRIMARY KEY,
	programId VARCHAR(36) NOT NULL,
    date VARCHAR(200) NOT NULL,
    start VARCHAR(200) NOT NULL,
	end VARCHAR(200) NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	createdBy VARCHAR(36),
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	updatedBy VARCHAR(36),
	FOREIGN KEY (programId)
		REFERENCES Programs (id)
		ON DELETE CASCADE,
	FOREIGN KEY (createdBy)
		REFERENCES Users (id),
	FOREIGN KEY (updatedBy)
		REFERENCES Users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO SystemInfo (version, migration) VALUES ('1.0.0', 1);